# Generated by Django 5.2.7 on 2026-02-17 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('manager', 'Manager-wise Report'), ('department', 'Department-wise Report')], help_text='Type of report (weekly, monthly, manager, department)', max_length=20)),
                ('year', models.PositiveSmallIntegerField(help_text='Report year (e.g., 2025)')),
                ('week_number', models.PositiveSmallIntegerField(blank=True, help_text='Week number (used for weekly/manager/department reports)', null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='Month number (used for monthly reports)', null=True)),
                ('payload', models.JSONField(help_text='Cached JSON data (aggregated summary, KPIs, and metrics).')),
                ('report_name', models.CharField(blank=True, help_text='Readable report name (auto-generated for dashboard display).', max_length=255)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.FileField(blank=True, help_text='Path to generated PDF/Excel file (if available).', null=True, upload_to='reports/')),
                ('is_active', models.BooleanField(default=True, help_text='Active or archived flag.')),
                ('department', models.ForeignKey(blank=True, help_text='Department reference (Master: DEPARTMENT)', limit_choices_to={'master_type': 'DEPARTMENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reports', to='masters.master')),
            ],
            options={
                'verbose_name': 'Cached Report',
                'verbose_name_plural': 'Cached Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
