# Generated by Django 5.2.7 on 2025-11-04 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('manager', 'Manager-wise Report'), ('department', 'Department-wise Report')], help_text='Type of report (weekly, monthly, manager, department)', max_length=20)),
                ('year', models.PositiveSmallIntegerField(help_text='Report year (e.g., 2025)')),
                ('week_number', models.PositiveSmallIntegerField(blank=True, help_text='Week number (used for weekly/manager/department reports)', null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='Month number (used for monthly reports)', null=True)),
                ('payload', models.JSONField(help_text='Cached JSON data (aggregated summary, KPIs, and metrics).')),
                ('report_name', models.CharField(blank=True, help_text='Readable report name (auto-generated for dashboard display).', max_length=255)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.FileField(blank=True, help_text='Path to generated PDF/Excel file (if available).', null=True, upload_to='reports/')),
                ('is_active', models.BooleanField(default=True, help_text='Active or archived flag.')),
                ('department', models.ForeignKey(blank=True, help_text='Department reference for department-wise reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reports', to='employee.department')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User or system that generated this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_reports', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Manager reference for manager-wise reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cached Report',
                'verbose_name_plural': 'Cached Reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['year'], name='reports_cac_year_0c30fb_idx'), models.Index(fields=['month'], name='reports_cac_month_0cc078_idx'), models.Index(fields=['week_number'], name='reports_cac_week_nu_698d31_idx'), models.Index(fields=['report_type'], name='reports_cac_report__d5447b_idx')],
                'constraints': [models.UniqueConstraint(fields=('report_type', 'year', 'week_number', 'month', 'manager', 'department'), name='unique_cached_report_per_period')],
            },
        ),
    ]
