# Generated by Django 5.2.7 on 2026-01-11 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_department_employee_de_code_bdee45_idx_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cachedreport',
            name='unique_cached_report_per_period',
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'weekly')), fields=('report_type', 'year', 'week_number'), name='unique_weekly_report'),
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'monthly')), fields=('report_type', 'year', 'month'), name='unique_monthly_report'),
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'manager')), fields=('report_type', 'year', 'week_number', 'manager'), name='unique_manager_weekly_report'),
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'department')), fields=('report_type', 'year', 'week_number', 'department'), name='unique_department_weekly_report'),
        ),
    ]
