# Generated by Django 5.2.7 on 2026-02-17 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='User or system that generated this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cachedreport',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager reference for manager-wise reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['year'], name='reports_cac_year_0c30fb_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['month'], name='reports_cac_month_0cc078_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['week_number'], name='reports_cac_week_nu_698d31_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedreport',
            index=models.Index(fields=['report_type'], name='reports_cac_report__d5447b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'weekly')), fields=('report_type', 'year', 'week_number'), name='unique_weekly_report'),
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'monthly')), fields=('report_type', 'year', 'month'), name='unique_monthly_report'),
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'manager')), fields=('report_type', 'year', 'week_number', 'manager'), name='unique_manager_weekly_report'),
        ),
        migrations.AddConstraint(
            model_name='cachedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'department')), fields=('report_type', 'year', 'week_number', 'department'), name='unique_department_weekly_report'),
        ),
    ]
