# Generated by Django 5.2.7 on 2025-11-04 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Short notification message or description.', max_length=255)),
                ('link', models.CharField(blank=True, help_text='Optional URL or route link for redirection (e.g., /reports/weekly/?week=44&year=2025)', max_length=255, null=True)),
                ('category', models.CharField(default='performance', help_text='Category of the notification (performance, feedback, system, etc.)', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the notification has been read.')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification was marked as read.', null=True)),
                ('auto_delete', models.BooleanField(default=True, help_text='If True → delete automatically after being read. If False → keep record marked as read.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created.')),
                ('department', models.ForeignKey(blank=True, help_text='Optional: department-wide notification scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='employee.department')),
                ('employee', models.ForeignKey(help_text='User who will receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'is_read'], name='notificatio_employe_a487d8_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
