# Generated by Django 5.2.7 on 2026-01-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('JOIN', 'Initial Join'), ('TRANSFER', 'Department Transfer'), ('AUTO_TRANSFER', 'Auto Transfer (System)'), ('DEPT_DEACTIVATION', 'Department Deactivated'), ('PROMOTION', 'Role Promotion'), ('DEMOTION', 'Role Demotion'), ('RESIGNATION', 'Employee Resignation'), ('TERMINATION', 'Employment Terminated')], max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee_department_history',
                'ordering': ['-joined_at'],
            },
        ),
    ]
