# Generated by Django 5.2.7 on 2026-01-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_initial'),
        ('employee_lifecycle', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedepartmenthistory',
            name='action_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedepartmenthistory',
            name='department',
            field=models.ForeignKey(limit_choices_to={'master_type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_departments', to='masters.master'),
        ),
        migrations.AddField(
            model_name='employeedepartmenthistory',
            name='designation',
            field=models.ForeignKey(limit_choices_to={'master_type': 'DESIGNATION'}, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_designations', to='masters.master'),
        ),
        migrations.AddField(
            model_name='employeedepartmenthistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_history', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeedepartmenthistory',
            name='role',
            field=models.ForeignKey(limit_choices_to={'master_type': 'ROLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_roles', to='masters.master'),
        ),
        migrations.AddIndex(
            model_name='employeedepartmenthistory',
            index=models.Index(fields=['employee', 'joined_at'], name='employee_de_employe_d8b835_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedepartmenthistory',
            index=models.Index(fields=['department'], name='employee_de_departm_baa944_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedepartmenthistory',
            index=models.Index(fields=['movement_type'], name='employee_de_movemen_1032f2_idx'),
        ),
    ]
