# Generated by Django 5.2.7 on 2026-01-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('master_type', models.CharField(choices=[('ROLE', 'Role'), ('DEPARTMENT', 'Department'), ('DESIGNATION', 'Designation'), ('PROJECT', 'Project'), ('METRIC', 'Metric')], db_index=True, help_text='Type of master data', max_length=20)),
                ('name', models.CharField(help_text='Name of the master entry', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=500, null=True)),
                ('code', models.CharField(blank=True, help_text='Short code (for departments, etc.)', max_length=20, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', help_text='Active or Inactive status', max_length=10)),
                ('metadata', models.JSONField(blank=True, help_text='Additional flexible properties', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in UI')),
                ('is_system', models.BooleanField(default=False, help_text='System-level master, protected from deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, help_text='Marks the default/fallback department')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When department was deactivated', null=True)),
                ('deactivation_reason', models.TextField(blank=True, help_text='Reason for department deactivation', null=True)),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
                'db_table': 'masters',
                'ordering': ['master_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MasterAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STATUS_CHANGE', 'Status Changed')], max_length=20)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'master_audit_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'project_details',
            },
        ),
    ]
