# Generated by Django 5.2.7 on 2025-12-22 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('master_type', models.CharField(choices=[('ROLE', 'Role'), ('DEPARTMENT', 'Department'), ('PROJECT', 'Project'), ('METRIC', 'Metric')], db_index=True, help_text='Type of master data', max_length=20)),
                ('master_name', models.CharField(help_text='Name of the master entry', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=500, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Active or Inactive status', max_length=10)),
                ('metadata', models.JSONField(blank=True, help_text='Additional flexible properties', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in UI')),
                ('is_system', models.BooleanField(default=False, help_text='System-level master, protected from deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='masters.master')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
                'db_table': 'masters',
                'ordering': ['master_type', 'display_order', 'master_name'],
            },
        ),
        migrations.CreateModel(
            name='MasterAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STATUS_CHANGE', 'Status Changed')], max_length=20)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='masters.master')),
            ],
            options={
                'db_table': 'master_audit_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['master_type', 'status'], name='masters_master__0fccc7_idx'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['master_name'], name='masters_master__d364b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('master_type', 'master_name'), name='unique_active_master'),
        ),
        migrations.AddIndex(
            model_name='masterauditlog',
            index=models.Index(fields=['master', '-changed_at'], name='master_audi_master__69eaa8_idx'),
        ),
    ]
