# Generated by Django 5.2.7 on 2026-02-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default department')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Department Detail',
                'verbose_name_plural': 'Department Details',
                'db_table': 'department_details',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_type', models.CharField(choices=[('ROLE', 'Role'), ('DEPARTMENT', 'Department'), ('PROJECT', 'Project'), ('MEASUREMENT', 'Measurement')], db_index=True, help_text='Category of master data', max_length=20)),
                ('name', models.CharField(help_text='Display name of the master entry', max_length=100)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Short unique code (e.g., DEPT-001)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', help_text='Current status of the record', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Sort order for UI display')),
                ('is_system', models.BooleanField(default=False, help_text='System record - protected from deletion')),
                ('metadata', models.JSONField(blank=True, help_text='Flexible JSON storage for type-specific attributes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
                'db_table': 'masters',
                'ordering': ['master_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MasterAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STATUS_CHANGE', 'Status Changed')], help_text='Type of change performed', max_length=20)),
                ('old_data', models.JSONField(blank=True, help_text='Previous state snapshot', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='New state snapshot', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Client browser/agent', max_length=255)),
            ],
            options={
                'verbose_name': 'Master Audit Log',
                'verbose_name_plural': 'Master Audit Logs',
                'db_table': 'master_audit_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Project Detail',
                'verbose_name_plural': 'Project Details',
                'db_table': 'project_details',
            },
        ),
    ]
