# Generated by Django 5.2.7 on 2026-02-17 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdetails',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='master',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='master',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent entry for hierarchical structures', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masters.master'),
        ),
        migrations.AddField(
            model_name='master',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='master',
            field=models.OneToOneField(limit_choices_to={'master_type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='department_details', to='masters.master'),
        ),
        migrations.AddField(
            model_name='masterauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterauditlog',
            name='master',
            field=models.ForeignKey(help_text='Affected master record', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='masters.master'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='department',
            field=models.ForeignKey(help_text='Owning department', limit_choices_to={'master_type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='department_projects', to='masters.master'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='master',
            field=models.OneToOneField(help_text='Linked master record', limit_choices_to={'master_type': 'PROJECT'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='masters.master'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['master_type', 'status'], name='masters_master__0fccc7_idx'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['parent', 'master_type'], name='masters_parent__b8d92c_idx'),
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Active')), fields=('master_type', 'name'), name='unique_master_name_per_type'),
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('master_type', 'code'), name='unique_master_code_per_type'),
        ),
        migrations.AddIndex(
            model_name='masterauditlog',
            index=models.Index(fields=['master', '-changed_at'], name='master_audi_master__69eaa8_idx'),
        ),
        migrations.AddIndex(
            model_name='masterauditlog',
            index=models.Index(fields=['action', '-changed_at'], name='master_audi_action_7654b2_idx'),
        ),
    ]
