# Generated by Django 5.2.7 on 2025-12-23 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['master_type', 'display_order', 'name'], 'verbose_name': 'Master', 'verbose_name_plural': 'Masters'},
        ),
        migrations.RemoveConstraint(
            model_name='master',
            name='unique_active_master',
        ),
        migrations.RemoveIndex(
            model_name='master',
            name='masters_master__d364b3_idx',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='master_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='master',
            name='code',
            field=models.CharField(blank=True, help_text='Short code (for departments, etc.)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', help_text='Active or Inactive status', max_length=10),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['name'], name='masters_name_6c65f1_idx'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['code'], name='masters_code_8d1b59_idx'),
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Active')), fields=('master_type', 'name'), name='unique_active_master'),
        ),
    ]
