# Generated by Django 5.2.7 on 2026-01-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='master',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='Who deactivated the department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='master',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masters.master'),
        ),
        migrations.AddField(
            model_name='master',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterauditlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterauditlog',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='masters.master'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='department',
            field=models.ForeignKey(limit_choices_to={'master_type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='projects_by_department', to='masters.master'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_projects', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project',
            field=models.OneToOneField(limit_choices_to={'master_type': 'PROJECT'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='masters.master'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['master_type', 'status'], name='masters_master__0fccc7_idx'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['name'], name='masters_name_6c65f1_idx'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['code'], name='masters_code_8d1b59_idx'),
        ),
        migrations.AddIndex(
            model_name='masterauditlog',
            index=models.Index(fields=['master', '-changed_at'], name='master_audi_master__69eaa8_idx'),
        ),
    ]
