# Generated by Django 5.2.7 on 2026-02-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
