# Generated by Django 5.2.7 on 2025-12-23 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_master_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='master',
            name='unique_active_master',
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.UniqueConstraint(fields=('master_type', 'name', 'status'), name='unique_active_master'),
        ),
    ]
