# Generated by Django 5.2.7 on 2025-12-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_remove_master_unique_active_master_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='master',
            name='unique_active_master',
        ),
    ]
