# Generated by Django 5.2.7 on 2025-12-26 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
        ('masters', '0004_remove_master_unique_active_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(limit_choices_to={'master_type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='projects_by_department', to='masters.master')),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_projects', to='employee.employee')),
                ('project', models.OneToOneField(limit_choices_to={'master_type': 'PROJECT'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='masters.master')),
            ],
            options={
                'db_table': 'project_details',
            },
        ),
    ]
