# Generated by Django 5.2.7 on 2026-01-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
        ('masters', '0005_projectdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRoleAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, limit_choices_to={'master_type': 'DEPARTMENT'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_role_departments', to='masters.master')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='employee.employee')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_employees', to='employee.employee')),
                ('role', models.ForeignKey(limit_choices_to={'master_type': 'ROLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='employee_role_assignments', to='masters.master')),
            ],
            options={
                'db_table': 'employee_role_assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='employee_ro_employe_336196_idx'), models.Index(fields=['role', 'status'], name='employee_ro_role_id_241e65_idx')],
                'unique_together': {('employee', 'role')},
            },
        ),
    ]
