# Generated by Django 5.2.7 on 2026-01-11 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_employeeroleassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When department was deactivated', null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='Who deactivated the department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='master',
            name='deactivation_reason',
            field=models.TextField(blank=True, help_text='Reason for department deactivation', null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Marks the default/fallback department'),
        ),
        migrations.AddConstraint(
            model_name='master',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('master_type', 'DEPARTMENT')), fields=('is_default',), name='single_default_department'),
        ),
    ]
