# Generated by Django 5.2.7 on 2025-11-04 07:29

import django.db.models.deletion
import django.utils.timezone
import performance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('week_number', models.PositiveSmallIntegerField(default=performance.models.current_week_number)),
                ('year', models.PositiveSmallIntegerField(default=performance.models.current_year)),
                ('evaluation_period', models.CharField(blank=True, default='', help_text='E.g., Week 41 (07 Oct 2025 - 13 Oct 2025)', max_length=120)),
                ('evaluation_type', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Client', 'Client'), ('Self', 'Self')], default='Manager', help_text='Who conducted the evaluation.', max_length=20)),
                ('communication_skills', models.PositiveSmallIntegerField(default=0)),
                ('multitasking', models.PositiveSmallIntegerField(default=0)),
                ('team_skills', models.PositiveSmallIntegerField(default=0)),
                ('technical_skills', models.PositiveSmallIntegerField(default=0)),
                ('job_knowledge', models.PositiveSmallIntegerField(default=0)),
                ('productivity', models.PositiveSmallIntegerField(default=0)),
                ('creativity', models.PositiveSmallIntegerField(default=0)),
                ('work_quality', models.PositiveSmallIntegerField(default=0)),
                ('professionalism', models.PositiveSmallIntegerField(default=0)),
                ('work_consistency', models.PositiveSmallIntegerField(default=0)),
                ('attitude', models.PositiveSmallIntegerField(default=0)),
                ('cooperation', models.PositiveSmallIntegerField(default=0)),
                ('dependability', models.PositiveSmallIntegerField(default=0)),
                ('attendance', models.PositiveSmallIntegerField(default=0)),
                ('punctuality', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0, help_text='Sum of all metrics (max 1500).')),
                ('average_score', models.FloatField(default=0.0, help_text='Average score scaled to 100.')),
                ('rank', models.PositiveSmallIntegerField(blank=True, help_text='Ranking within department/week.', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department under which the evaluation is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_performances', to='employee.department')),
                ('employee', models.ForeignKey(help_text='Employee whose performance is being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='employee.employee')),
                ('evaluator', models.ForeignKey(blank=True, help_text='Admin, Manager, or Client who gave the evaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Evaluation',
                'verbose_name_plural': 'Performance Evaluations',
                'ordering': ['-review_date', '-created_at'],
                'indexes': [models.Index(fields=['employee'], name='performance_employe_2c0d9d_idx'), models.Index(fields=['department'], name='performance_departm_62f47e_idx'), models.Index(fields=['week_number', 'year'], name='performance_week_nu_ec6166_idx'), models.Index(fields=['evaluation_type'], name='performance_evaluat_5fdec2_idx'), models.Index(fields=['average_score'], name='performance_average_93415c_idx')],
                'unique_together': {('employee', 'week_number', 'year', 'evaluation_type')},
            },
        ),
    ]
