# Generated by Django 5.2.7 on 2026-02-17 09:20

import django.db.models.deletion
import django.utils.timezone
import performance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('week_number', models.PositiveSmallIntegerField(default=performance.models.current_week_number)),
                ('year', models.PositiveSmallIntegerField(default=performance.models.current_year)),
                ('evaluation_period', models.CharField(blank=True, default='', help_text='E.g., Week 41 (07 Oct 2025 - 13 Oct 2025)', max_length=120)),
                ('evaluation_type', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Client', 'Client'), ('Self', 'Self')], default='Manager', help_text='Who conducted the evaluation.', max_length=20)),
                ('communication_skills', models.PositiveSmallIntegerField(default=0)),
                ('multitasking', models.PositiveSmallIntegerField(default=0)),
                ('team_skills', models.PositiveSmallIntegerField(default=0)),
                ('technical_skills', models.PositiveSmallIntegerField(default=0)),
                ('job_knowledge', models.PositiveSmallIntegerField(default=0)),
                ('productivity', models.PositiveSmallIntegerField(default=0)),
                ('creativity', models.PositiveSmallIntegerField(default=0)),
                ('work_quality', models.PositiveSmallIntegerField(default=0)),
                ('professionalism', models.PositiveSmallIntegerField(default=0)),
                ('work_consistency', models.PositiveSmallIntegerField(default=0)),
                ('attitude', models.PositiveSmallIntegerField(default=0)),
                ('cooperation', models.PositiveSmallIntegerField(default=0)),
                ('dependability', models.PositiveSmallIntegerField(default=0)),
                ('attendance', models.PositiveSmallIntegerField(default=0)),
                ('punctuality', models.PositiveSmallIntegerField(default=0)),
                ('communication_skills_comment', models.TextField(blank=True, null=True)),
                ('multitasking_comment', models.TextField(blank=True, null=True)),
                ('team_skills_comment', models.TextField(blank=True, null=True)),
                ('technical_skills_comment', models.TextField(blank=True, null=True)),
                ('job_knowledge_comment', models.TextField(blank=True, null=True)),
                ('productivity_comment', models.TextField(blank=True, null=True)),
                ('creativity_comment', models.TextField(blank=True, null=True)),
                ('work_quality_comment', models.TextField(blank=True, null=True)),
                ('professionalism_comment', models.TextField(blank=True, null=True)),
                ('work_consistency_comment', models.TextField(blank=True, null=True)),
                ('attitude_comment', models.TextField(blank=True, null=True)),
                ('cooperation_comment', models.TextField(blank=True, null=True)),
                ('dependability_comment', models.TextField(blank=True, null=True)),
                ('attendance_comment', models.TextField(blank=True, null=True)),
                ('punctuality_comment', models.TextField(blank=True, null=True)),
                ('total_score', models.PositiveIntegerField(default=0, help_text='Sum of all metrics (max 1500).')),
                ('average_score', models.FloatField(default=0.0, help_text='Average score scaled to 100.')),
                ('rank', models.PositiveSmallIntegerField(blank=True, help_text='Ranking within department/week.', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department under which the evaluation is recorded.', limit_choices_to={'master_type': 'DEPARTMENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_performances', to='masters.master')),
                ('employee', models.ForeignKey(help_text='Employee whose performance is being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Performance Evaluation',
                'verbose_name_plural': 'Performance Evaluations',
                'ordering': ['-review_date', '-created_at'],
            },
        ),
    ]
