# Generated by Django 5.2.7 on 2025-11-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performanceevaluation',
            unique_together=set(),
        ),
    ]
