# Generated by Django 5.2.7 on 2026-02-17 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_initial'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, help_text='Admin, Manager, or Client who gave the evaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_metrics', to='performance.performanceevaluation'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='measurement',
            field=models.ForeignKey(limit_choices_to={'master_type': 'MEASUREMENT'}, on_delete=django.db.models.deletion.PROTECT, to='masters.master'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['employee'], name='performance_employe_2c0d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['department'], name='performance_departm_62f47e_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['week_number', 'year'], name='performance_week_nu_ec6166_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['evaluation_type'], name='performance_evaluat_5fdec2_idx'),
        ),
        migrations.AddConstraint(
            model_name='performanceevaluation',
            constraint=models.UniqueConstraint(fields=('employee', 'week_number', 'year', 'evaluation_type'), name='unique_employee_week_year_evaluation'),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together={('evaluation', 'measurement')},
        ),
    ]
