# Generated by Django 5.2.7 on 2025-11-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_alter_performanceevaluation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='attendance_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='attitude_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='communication_skills_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='cooperation_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='creativity_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='dependability_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='job_knowledge_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='multitasking_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='productivity_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='professionalism_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='punctuality_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='team_skills_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='technical_skills_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='work_consistency_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='work_quality_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
