# Generated by Django 5.2.7 on 2025-11-20 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
        ('performance', '0003_performanceevaluation_attendance_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='performanceevaluation',
            name='performance_average_93415c_idx',
        ),
        migrations.AddConstraint(
            model_name='performanceevaluation',
            constraint=models.UniqueConstraint(fields=('employee', 'week_number', 'year', 'evaluation_type'), name='unique_employee_week_year_evaluation'),
        ),
    ]
