# Generated by Django 5.2.7 on 2025-11-04 07:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short department code (e.g., ENG01)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Department name (e.g., Engineering)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional department description.', null=True)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='employee_de_code_bdee45_idx'), models.Index(fields=['name'], name='employee_de_name_1adfec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(blank=True, help_text='Project the employee is working on', max_length=150, null=True)),
                ('reporting_manager_name', models.CharField(blank=True, help_text="Reporting manager's name", max_length=150, null=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, help_text='Date of birth (DD-MM-YYYY)', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture (JPG/PNG)', null=True, upload_to='profile_pics/%Y/%m/%d')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=12, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for employee.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department this employee belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.department')),
                ('manager', models.ForeignKey(blank=True, help_text='Reporting manager for this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['user__emp_id'],
            },
        ),
    ]
