# Generated by Django 5.2.7 on 2026-01-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(help_text='Department (Master-based)', limit_choices_to={'master_type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='masters.master'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='Designation (Master-based)', limit_choices_to={'master_type': 'DESIGNATION'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_by_designation', to='masters.master'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Reporting manager for this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(help_text='Role (Master-based)', limit_choices_to={'master_type': 'ROLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='employees_by_role', to='masters.master'),
        ),
    ]
