# Generated by Django 5.2.7 on 2026-01-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='department',
            name='employee_de_code_bdee45_idx',
        ),
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]
