# Generated by Django 5.2.7 on 2026-02-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, db_index=True, help_text='Employee designation (manual entry)', max_length=100, null=True),
        ),
    ]
