# Generated by Django 5.2.7 on 2026-01-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, db_index=True, help_text='Employee designation entered manually (e.g. Senior Data Analyst)', max_length=100, null=True),
        ),
    ]
