# Generated by Django 5.2.7 on 2026-02-20 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('masters', '0003_alter_master_code'),
        ('users', '0003_user_temp_password'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='joining_date_not_future',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('joining_date__lte', datetime.date(2026, 2, 20))), name='joining_date_not_future'),
        ),
    ]
