# Generated by Django 5.2.7 on 2026-01-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(db_index=True, help_text='Employee ID entered manually by Admin (e.g., EMP0001)', max_length=50, unique=True),
        ),
    ]
