# Generated by Django 5.2.7 on 2025-11-04 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(help_text='Detailed feedback or comments.')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or context.', null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (scale: 1–10).')),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether feedback is visible in employee dashboards.', max_length=20)),
                ('feedback_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(blank=True, editable=False, help_text='Auto-filled (Admin / Manager / Client) for analytics grouping.', max_length=20, null=True)),
                ('client_name', models.CharField(blank=True, help_text="Client's name or organization.", max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who submitted this feedback (Admin / Manager / Client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department under which the feedback is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department')),
                ('employee', models.ForeignKey(help_text='Employee receiving this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedback',
            },
        ),
        migrations.CreateModel(
            name='GeneralFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(help_text='Detailed feedback or comments.')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or context.', null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (scale: 1–10).')),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether feedback is visible in employee dashboards.', max_length=20)),
                ('feedback_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(blank=True, editable=False, help_text='Auto-filled (Admin / Manager / Client) for analytics grouping.', max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who submitted this feedback (Admin / Manager / Client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department under which the feedback is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department')),
                ('employee', models.ForeignKey(help_text='Employee receiving this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to='employee.employee')),
            ],
            options={
                'verbose_name': 'General Feedback',
                'verbose_name_plural': 'General Feedback',
            },
        ),
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(help_text='Detailed feedback or comments.')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or context.', null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Numeric rating (scale: 1–10).')),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', help_text='Defines whether feedback is visible in employee dashboards.', max_length=20)),
                ('feedback_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(blank=True, editable=False, help_text='Auto-filled (Admin / Manager / Client) for analytics grouping.', max_length=20, null=True)),
                ('manager_name', models.CharField(blank=True, help_text='Auto-filled with Manager’s name if available.', max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who submitted this feedback (Admin / Manager / Client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department under which the feedback is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_feedbacks', to='employee.department')),
                ('employee', models.ForeignKey(help_text='Employee receiving this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feedbacks', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Manager Feedback',
                'verbose_name_plural': 'Manager Feedback',
            },
        ),
    ]
